export const LIGHT_ICON = require('../assets/images/light.png')
export const BACKGROUND_ICON = require('../assets/images/loginBackground.jpg')
export const LOGO = require('../assets/images/logo.jpeg')
export const SPLASH_ICON = require('../assets/images/splashLogo.png')
export const PERSON_ICON = require('../assets/images/person.png')
export const PERSON_BLACK_ICON = require('../assets/images/personBlack.png')
